### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by alastair** [alastair/python-musicbrainzngs#10]

**Comment by JonnyJD** [comment]
@alastair: please review if want to introduce explicit unit testing or if the "indirect" testing we currently do is enough.

I personally would close this issue and just keep improving the tests we currently do.
We do test mbxml and "non-mbxml" separately, which has a similar intent.

**Comment by alastair** [comment]
We have many more tests than we did when I opened this, and I believe we're pretty good at adding new ones. Solved for now!
