### ISSUE TITLE
Search query escaping when using Lucene "Range Searches" 

### ISSUE THREAD

**Issue by ohrstrom** [alastair/python-musicbrainzngs#121]
It looks like musicbrainz-ngs does not properly encode the search query when using the ["Range Search"](https://lucene.apache.org/core/4_3_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Range_Searches) syntax. I'm not totally sure if I did something wrong.. but in my understanding the following search:

```
...
date='[1996-01-01 TO 1996-12-31]',
...
```

should generate the following query string:

```
+date%3A%5B1996%5C-01%5C-01+TO+1996%5C-12%5C-31%5D
```

instead musicbrainz-ngs escapes it as:

```
+date%3A%22%5C%5B1996%5C-01%5C-01+TO+1996%5C-12%5C-31%5C%5D
```

try:
http://musicbrainz.org/ws/2/recording/?query=%22%5C%22Street+Life%5C%22%22+AND+date%3A%5B1996%5C-01%5C-01+TO+1996%5C-12%5C-31%5D

vs
http://musicbrainz.org/ws/2/recording/?query=%22%5C%22Street+Life%5C%22%22+AND+date%3A%22%5C%5B1996%5C-01%5C-01+TO+1996%5C-12%5C-31%5C%5D

**Comment by typistX** [comment]
I'm using `query` in order to get the same results as musicbrainz (see #224), but I'd still like special characters like `/` and `!` escaped. How can this be achieved?
