### ISSUE TITLE
Set server port

### ISSUE THREAD

**Issue by sampsyo** [alastair/python-musicbrainzngs#122]
We currently allow clients of the library to set the hostname for the MusicBrainz API server. Especially in the case of the server VM, which defaults to port 5000, it would also be useful to set a custom port number.

I'm guessing the way to go is to add an optional parameter to `set_hostname()`. Any objections?

As mentioned in sampsyo/beets#365.

**Comment by JonnyJD** [comment]
I am going through old issues and there is even a duplicate for this: #141.

Reason enough to mention setting a port in the docstring, done with efdf967787c87109ad8774e866d8b84d025a10c3.
