### ISSUE TITLE
get_releases_by_discid() fails when include includes 'annotation'

### ISSUE THREAD

**Issue by clach04** [alastair/python-musicbrainzngs#160]
https://python-musicbrainzngs.readthedocs.org/en/latest/api/#general for `get_releases_by_discid()` documents:

Available includes: artists, labels, recordings, release-groups, media, artist-credits, discids, isrcs, recording-level-rels, work-level-rels, annotation, aliases, tags, user-tags, area-rels, artist-rels, label-rels, place-rels, recording-rels, release-rels, release-group-rels, series-rels, url-rels, work-rels

using annotation fails with:

      File "musicbrainz.py", line 221, in _check_includes_impl
        "%s is not a valid include" % i)
    musicbrainzngs.musicbrainz.InvalidIncludeError: Bad includes: annotation is not a valid include

I don't know enough about the underlying webservice to know if this supposed to work (bug in python-musicbrainzngs) or not expected to work and thus a doc bug in python-musicbrainzngs :-(

Bug script:

    import musicbrainzngs as m

    m.set_useragent("application", "0.01", "http://example.com")
    print m.get_releases_by_discid("O4vVwye6t1VOH3FvQHR5uWPt268-", includes=["annotation"])

**Comment by alastair** [comment]
We had 2 bugs here - one was that the validtion for `get_releases_by_discid` was showing the includes list for `get_release_by_id`, and the second was that the includes for discid should be the same as release. Fixed!

**Comment by clach04** [comment]
I'm getting a different error with the fix in place. the doc string looks good but there is now a HTTP Error 400: Bad Request:

    import musicbrainzngs as m

    m.set_useragent("application", "0.01", "http://example.com")
    print m.get_releases_by_discid.__doc__
    print m.get_releases_by_discid("O4vVwye6t1VOH3FvQHR5uWPt268-")
    print m.get_releases_by_discid("O4vVwye6t1VOH3FvQHR5uWPt268-", includes=["annotation"])


output

    >c:\python27\pythonw -u "bug.py"
    Search for releases with a :musicbrainz:`Disc ID` or table of contents.

        When a `toc` is provided and no release with the disc ID is found,
        a fuzzy search by the toc is done.
        The `toc` should have to same format as :attr:`discid.Disc.toc_string`.
        When a `toc` is provided, the format of the discid itself is not
        checked server-side, so any value may be passed if searching by only
        `toc` is desired.

        If no toc matches in musicbrainz but a :musicbrainz:`CD Stub` does,
        the CD Stub will be returned. Prevent this from happening by
        passing `cdstubs=False`.

        By default only results that match a format that allows discids
        (e.g. CD) are included. To include all media formats, pass
        `media_format='all'`.

        The result is a dict with either a 'disc' , a 'cdstub' key
        or a 'release-list' (fuzzy match with TOC).
        A 'disc' has a 'release-list' and a 'cdstub' key has direct 'artist'
        and 'title' keys.

        *Available includes*: artists, labels, recordings, release-groups, media, artist-credits, discids, isrcs, recording-level-rels, work-level-rels, annotation, aliases, area-rels, artist-rels, label-rels, place-rels, recording-rels, release-rels, release-group-rels, series-rels, url-rels, work-rels
    {'disc': {'release-count': 1, 'release-list': [{'status': 'Official', 'release-event-count': 1, 'barcode': '881824107720', 'title': 'I Choose Noise', 'country': 'GB', 'medium-count': 1, 'cover-art-archive': {'count': '3', 'front': 'true', 'back': 'true', 'artwork': 'true'}, 'release-event-list': [{'date': '2006-09-04', 'area': {'sort-name': 'United Kingdom', 'iso-3166-1-code-list': ['GB'], 'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'name': 'United Kingdom'}}], 'medium-list': [{'position': '1', 'track-count': 11, 'format': 'CD', 'disc-list': [{'id': 'O4vVwye6t1VOH3FvQHR5uWPt268-', 'sectors': '324154'}], 'track-list': [], 'disc-count': 1}], 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'date': '2006-09-04', 'quality': 'normal', 'id': 'c225674c-3df6-4c02-8b28-c53a2f6472ef', 'asin': 'B000H80LDQ'}], 'id': 'O4vVwye6t1VOH3FvQHR5uWPt268-', 'sectors': '324154'}}
    Traceback (most recent call last):
      File "bug.py", line 6, in <module>
        print m.get_releases_by_discid("O4vVwye6t1VOH3FvQHR5uWPt268-", includes=["annotation"])
      File "C:\Users\clach04\py\python-musicbrainzngs\musicbrainzngs\musicbrainz.py", line 967, in get_releases_by_discid
        return _do_mb_query("discid", id, includes, params)
      File "C:\Users\clach04\py\python-musicbrainzngs\musicbrainzngs\musicbrainz.py", line 686, in _do_mb_query
        return _mb_request(path, 'GET', auth_required, args=args)
      File "C:\Users\clach04\py\python-musicbrainzngs\musicbrainzngs\musicbrainz.py", line 386, in __call__
        return self.fun(*args, **kwargs)
      File "C:\Users\clach04\py\python-musicbrainzngs\musicbrainzngs\musicbrainz.py", line 651, in _mb_request
        resp = _safe_read(opener, req, body)
      File "C:\Users\clach04\py\python-musicbrainzngs\musicbrainzngs\musicbrainz.py", line 472, in _safe_read
        raise ResponseError(cause=exc)
    musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 400: Bad Request
    >Exit code: 1

**Comment by mineo** [comment]
I've reported that as a bug in [MBS-8171](http://tickets.musicbrainz.org/browse/MBS-8171).
