### ISSUE TITLE
Python 3.4 tests break with tox >= 2

### ISSUE THREAD

**Issue by mineo** [alastair/python-musicbrainzngs#167]
While running tests for #165 most of the tests that deal with external data failed on Python 3.4, but only when run with a tox version >= 2:

> ======================================================================
> ERROR: testFields (test.test_mbxml_search.SearchArtistTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
  > File "/home/wieland/dev/python-musicbrainzngs/test/test_mbxml_search.py", line 50, in testFields
    > res = mbxml.parse_message(msg)
  > File "/home/wieland/dev/python-musicbrainzngs/musicbrainzngs/mbxml.py", line 133, in parse_message
    > tree = util.bytes_to_elementtree(message)
  > File "/home/wieland/dev/python-musicbrainzngs/musicbrainzngs/util.py", line 37, in bytes_to_elementtree
    > s = bytes_or_file.read()
  > File "/home/wieland/dev/python-musicbrainzngs/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
    > return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1577: ordinal not in range(128)
>
> ======================================================================
> ERROR: testFields (test.test_mbxml_search.SearchWorkTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
  > File "/home/wieland/dev/python-musicbrainzngs/test/test_mbxml_search.py", line 83, in testFields
    > res = mbxml.parse_message(msg)
  > File "/home/wieland/dev/python-musicbrainzngs/musicbrainzngs/mbxml.py", line 133, in parse_message
    > tree = util.bytes_to_elementtree(message)
  > File "/home/wieland/dev/python-musicbrainzngs/musicbrainzngs/util.py", line 37, in bytes_to_elementtree
    > s = bytes_or_file.read()
  > File "/home/wieland/dev/python-musicbrainzngs/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
    > return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 2911: ordinal not in range(128)
>
> ======================================================================
> ERROR: testWorkAliases (test.test_mbxml_work.GetWorkTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
  > File "/home/wieland/dev/python-musicbrainzngs/test/test_mbxml_work.py", line 35, in testWorkAliases
    > res = _common.open_and_parse_test_data(self.datadir, "3d7c7cd2-da79-37f4-98b8-ccfb1a4ac6c4-aliases.xml")
  > File "/home/wieland/dev/python-musicbrainzngs/test/_common.py", line 74, in open_and_parse_test_data
    > res = musicbrainzngs.mbxml.parse_message(msg)
  > File "/home/wieland/dev/python-musicbrainzngs/musicbrainzngs/mbxml.py", line 133, in parse_message
    > tree = util.bytes_to_elementtree(message)
  > File "/home/wieland/dev/python-musicbrainzngs/musicbrainzngs/util.py", line 37, in bytes_to_elementtree
    > s = bytes_or_file.read()
  > File "/home/wieland/dev/python-musicbrainzngs/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
    > return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 1345: ordinal not in range(128)

Simply running `python3.4 setup.py test` or using an older tox version works, so I guess this is similar to https://github.com/audreyr/cookiecutter/pull/453 and https://github.com/pydanny/cached-property/issues/22. It's probably a good thing this breaks because it looks like what causes it is that we're somewhere relying on some automatic utf8-de/encoding to happen but don't explicitly state that.

**Comment by sampsyo** [comment]
Yep! Beets went through this too: https://github.com/sampsyo/beets/issues/1461

**Comment by mineo** [comment]
I've added 3.5 to tox in d5be7bdab74dc6c1f6e3649d5ef82bcfa3ab34fe. During that change, I noticed that I can't reproduce this bug anymore on tox 2.1.1, but 2.0.1 still causes those failures, so I'll leave this issue open.

**Comment by alastair** [comment]
Tox changed this in 2.0.2 to pass `LANG` in to the environment - http://tox.readthedocs.org/en/latest/changelog.html#id5
Because we're only seeing this behaviour on 2.0.0 and 2.0.1 (with 2.2.x already out) I'm happy to close it.
