### ISSUE TITLE
submit tags method always requires a list of arguments

### ISSUE THREAD

**Issue by alastair** [alastair/python-musicbrainzngs#172]
If you use

    submit_tags(recording_tags={"mbid": "onetag"})

then we will add the tags `o`, `n`, `e`, `t`, `a`, and `g`. Perhaps this isn't what we expected... If there is just one string as an argument we treat it as a single tag.

**Comment by JonnyJD** [comment]
This should probably work as for isrcs:
```
rec2isrcs[rec] = isrcs if isinstance(isrcs, list) else [isrcs]
```

**Comment by alastair** [comment]
I agree. We do the same with includes as well, so it's a good idea to have
enverything consistent.

**Comment by alastair** [comment]
Merged
