### ISSUE TITLE
Leave alpha state

### ISSUE THREAD

**Issue by mineo** [alastair/python-musicbrainzngs#173]
The classifiers in setup.py advertise this as being in alpha state, but we're already careful to not break the api (#116) and beets (maybe others) already use this library without experiencing problems constantly. I think we're at least in beta now.

**Comment by alastair** [comment]
For consideration https://github.com/alastair/python-musicbrainzngs/commit/facd11f8e6cddb1bb06f00e854d98be93f2cba00

How about we jump straight to stable? You're right, we are careful about API changes and are successfully used by a *lot* of people.

**Comment by sampsyo** [comment]
A full 1.0 release sounds great to me! Maybe we can make the Requests-dependent version (#123) into 2.0 or something. :smiley:

**Comment by rlhelinski** [comment]
I meant to reply earlier: My project
<https://github.com/rlhelinski/musicbrainz-catalog> is using this library
and has enjoyed the features and haven't really had any issues with things
changing. I second the switch to stable, 1.0, etc.

Ryan

**Comment by alastair** [comment]
Ooo, this raised a discussion that I wasn't really expecting ;)
If people really want a 1.0 release then we can make it, though to me I'm content to move to stable but keep our nicely increasing 0.x numbers.

My rough thoughts were that we could do a release of 0.6 with all of our missing schema change endpoints, then 0.7 with requests. Perhaps 0.7 should be called 1.0 if enough people vote for it. Or do we have another bugfix release between them?

**Comment by JonnyJD** [comment]
It would be fine to just name the 0.6 or 0.7 release "1.0" to indicate we are stable now.
Having requests as a dependency when moving to 1.0 is fine, too. I would even recommend that.
This is somewhat easy to handle for packagers as dependencies are easier to handle than actual changes in the API.
Together with an announcement that this is fully compatible to 0.x.

We could then do compatible changes in 1.x and the next incompatible release would be 2.0.
(http://semver.org)

When/how to do 2.0 is a different discussion. When we start 2.0 we should only make bugfix releases for 1.0, I'd say.

**Comment by mineo** [comment]
I've merged facd11f because everybody seems to agree that the code (especially the API that other projects actually use) is stable. Whether or not we want to move to 1.0 or something else on the next version, I don't know.
