### ISSUE TITLE
Load number of releases and last release before specific date

### ISSUE THREAD

**Issue by inkrement** [alastair/python-musicbrainzngs#178]
Hi,
I have to load the number of all releases by a specific artist (given his mbid) and the date of the last release before a specific reference date. To achieve these goals I have two questions:

1) How can I use this python lib to call "http://musicbrainz.org/ws/2/release?artist=20244d07-534f-4eff-b4d4-930878889970&limit=1" and extract the count-attribute of the release-list element? IMHO this would be the fastest way to fetch the number of all releases. 

2) How can I fetch the date of the last release quite before a given date? Or do I have to fetch all releases by some artist mbid and iterate?

**Comment by mineo** [comment]
1) That's a browse request, therefore use `browse_releases(artist="20244d07-534f-4eff-b4d4-930878889970", limit=1)`.

2) I'm not aware of this being possible with browse/lookup requests. You should be able to use [Range Searches](https://lucene.apache.org/core/4_3_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Range_Searches) with the search web service like https://musicbrainz.org/ws/2/release/?query=arid:20244d07-534f-4eff-b4d4-930878889970%20AND%20date:[1999-01-01%20TO%202006-10-25] (or `search_releases(query="arid:20244d07-534f-4eff-b4d4-930878889970 AND date:[1999-01-01 TO 2006-10-25]")`) (note that releases without a month and day sort even before year-00-00).

**Comment by inkrement** [comment]
Thanks!
