### ISSUE TITLE
Getting instrument metadata

### ISSUE THREAD

**Issue by sertansenturk** [alastair/python-musicbrainzngs#182]
When I try mb.get_instrument_by_id('b9692581-c117-47f3-9524-3deeb69c6d3f'), I get an empty dictionary. Am I doing something wrong or can this call be broken?

**Comment by mineo** [comment]
`get_instrument_by_id` snuck in with 913059f45993f372a441b37cc5b052ea4e18fe2c but that obviously doesn't contain any code to actually parse the result. Looks like the code is unfortunately broken :cry:

**Comment by alastair** [comment]
Fixed!
