### ISSUE TITLE
Last release does not includes Covert Art Archive API client

### ISSUE THREAD

**Issue by EliotBerriot** [alastair/python-musicbrainzngs#185]
I'm trying to use the covert art archive client in a project of mine. According to [the documentation](http://python-musicbrainzngs.readthedocs.org/en/latest/usage/#cover-art-data), all I need to do is to use the `musicbrainzngs.caa.get_image()` method. However, using the last release of the package (`0.5`), I cannot access this function.

    >>> musicbrainzngs.get_image
    AttributeError: 'module' object has no attribute 'get_image'

    >>> import musicbrainzngs.caa
    No module named 'musicbrainzngs.caa'

After furthur investigation, it seems the last release was made on 2014-02-06, while the `caa.py` module was added on march 2014. 

Is there any chance you could make a new release on PyPI including the missing module ?

**Comment by alastair** [comment]
Thanks for letting us know this. A new release is something that many people have asked for. We're working on finishing up a few more things (https://github.com/alastair/python-musicbrainzngs/milestones/0.6) and hopefully will make a new release before the new year

**Comment by EliotBerriot** [comment]
Thanks for the fast answer ! I'm glad to know a new release is coming up. As there is nothing urgent in my case, I'll wait a few weeks until the new release is pushed to PyPi. 

And thanks for the package anyway, it works great :)

**Comment by alastair** [comment]
released!
