### ISSUE TITLE
get_release_by_id() missing contributor data

### ISSUE THREAD

**Issue by shaolo1** [alastair/python-musicbrainzngs#202]
When I visit a release page like [Best Classics 100](http://musicbrainz.org/release/bf7c6e31-ce71-4c85-9cfc-101c2fb7419b) the artist credits list contains role information, ie, composer, conductor, orchestra.  Looking at the source of the web page shows this data in json blocks like the following

```
"contributor":[
{"roleName":"conductor","@type":"OrganizationRole",
"contributor":{"@type":["Person","MusicGroup"],
"@id":"https://musicbrainz.org/artist/afb8d624-52d7-4a72-8d0b-62fff3e29f79",
"name":"Sir Neville Marriner"}},
{"roleName":"orchestra","@type":"OrganizationRole",
"contributor":{"@type":"MusicGroup","name":"Academy of St Martin in the Fields",
"@id":"https://musicbrainz.org/artist/f0ac992d-edd9-4672-ac23-ba0ca93f6539"}}],

```
When using the api as follows the credits show the artists, but the roles are missing.

```
    result = musicbrainzngs.get_release_by_id(
        'bf7c6e31-ce71-4c85-9cfc-101c2fb7419b',
        includes=["artists", "labels", "recordings", "release-groups", "media", "artist-credits", "discids", "isrcs", "recording-level-rels", "work-level-rels", "annotation", "aliases", "area-rels", "artist-rels", "label-rels", "place-rels", "recording-rels", "release-rels", "release-group-rels", "url-rels", "work-rels"])

```

Am I doing something wrong, or is there any way to get the contributor/role information?

**Comment by alastair** [comment]
This data is included in the `artist-relation-list` element of each recording in the release.
For example, with your query:

```json
In [21]: result["release"]["medium-list"][0]["track-list"][0]["recording"]["artist-relation-list"][0]
Out[21]:
{'artist': {'id': 'afb8d624-52d7-4a72-8d0b-62fff3e29f79',
  'name': 'Sir Neville Marriner',
  'sort-name': 'Marriner, Neville, Sir'},
 'direction': 'backward',
 'target': 'afb8d624-52d7-4a72-8d0b-62fff3e29f79',
 'type': 'conductor',
 'type-id': '234670ce-5f22-4fd0-921b-ef1662695c5d'}
```

**Comment by shaolo1** [comment]
Thank you so much!  I would have never figured that out.

For anyone else, interested, the minimum set of includes to get that information is as follows

`includes=["artists", "artist-rels", "recording-level-rels", "recordings"]
`

**Comment by shaolo1** [comment]
Thank you so much!  I would have never figured that out.

For anyone else, interested, the minimum set of includes to get that information is as follows

`includes=["artists", "artist-rels", "recording-level-rels", "recordings"]
`

**Comment by shaolo1** [comment]
Looking further, I do not see the "recording of" block...

```

recording of:
    Solomon, HWV 67: Act III. Sinfonia "The Arrival of the Queen of Sheba"

    composer:
        George Frideric Handel (German‐British baroque composer) (1748)

    arrangements:
        The Arrival of the Queen of Sheba 
    part of:
        Solomon, HWV 67: Act III 
    referred to in medleys:
        Hooked on Classics, Part 3 


```

Is an additional query required to get that information?

**Comment by alastair** [comment]
This is a recording-work level relationship. You should be able to get it by using `get_recording_by_id` with `includes=["work-rels"]`
Please refer to the [MusicBrainz documentation](http://musicbrainz.org/doc/Development/XML_Web_Service/Version_2) for a description of how this data connects together
