### ISSUE TITLE
Using the bindings with local musicbrainz server

### ISSUE THREAD

**Issue by GeorgeL9** [alastair/python-musicbrainzngs#216]
I have my own local copy of musicbrainz server and would prefer to query against it, rather than the public one. Is this possible?

**Comment by alastair** [comment]
Yes, use http://python-musicbrainzngs.readthedocs.io/en/v0.6/api/#musicbrainzngs.set_hostname

You probably also want to disable the built-in rate limiting: http://python-musicbrainzngs.readthedocs.io/en/v0.6/api/#musicbrainzngs.set_rate_limit
