### ISSUE TITLE
max_retries on _safe_read is not-changeable

### ISSUE THREAD

**Issue by iTaybb** [alastair/python-musicbrainzngs#218]
The number of max_retries is restricted to 8 on the signature of the _safe_read function.

I think it should be a variable that you can set, with something like `musicbrainzngs.set_max_retries`.

I can make the commits - do you have any objections for that?

**Comment by iTaybb** [comment]
Ah, sorry, I just saw that issue #174 is talking about that. I'll create the commits then

**Comment by alastair** [comment]
Fixed in #219
