### ISSUE TITLE
search_recordings ignores country

### ISSUE THREAD

**Issue by phynias** [alastair/python-musicbrainzngs#222]
for some reason when i try and run a search_recordings when i add the country= it ignores it and returns albums from every country. not sure what i am doing wrong.

`res = mb.search_recordings(limit=5, artist=tag.artist, recording=tag.title, type='Album', country='US', format='cd', strict=True)
`

> {   'country': 'XW',
>     'date': '2013-11-25',
>     'id': '4d2cda96-9543-44b8-858a-62eb98715eec',
>     'medium-list': [   {   'format': 'Digital Media',
>                            'position': '1',
>                            'track-count': 18,
>                            'track-list': [   {   'id': '5ffded0d-0e1b-4891-95ad-0c1041796782',
>                                                  'length': '245000',
>                                                  'number': '2',
>                                                  'title': 'Story of My Life',
>                                                  'track_or_recording_length': '245000'}]}],
>     'medium-track-count': 18,
>     'release-event-list': [   {   'area': {   'id': '525d4e18-3d00-31b9-a58b-a146a916de8f',
>                                               'iso-3166-1-code-list': [   'XW'],
>                                               'name': '[Worldwide]',
>                                               'sort-name': '[Worldwide]'},
>                                   'date': '2013-11-25'}],
>     'release-group': {   'id': '81f9c781-683e-4a4e-ba86-799e3c4c4be9',
>                          'primary-type': 'Album',
>                          'type': 'Album'},
>     'status': 'Official',
>     'title': 'Midnight Memories: The Ultimate Edition'}
> None
> {   'country': 'GB',
>     'date': '2013-11-25',
>     'id': '075f6d85-6cf2-4c4b-89a1-05a62a7f07e0',
>     'medium-list': [   {   'format': 'CD',
>                            'position': '1',
>                            'track-count': 18,
>                            'track-list': [   {   'id': 'e670ad69-8e2d-45f3-ab31-3d2d7145c052',
>                                                  'length': '245493',
>                                                  'number': '2',
>                                                  'title': 'Story of My Life',
>                                                  'track_or_recording_length': '245493'}]}],
>     'medium-track-count': 18,
>     'release-event-list': [   {   'area': {   'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
>                                               'iso-3166-1-code-list': [   'GB'],
>                                               'name': 'United Kingdom',
>                                               'sort-name': 'United Kingdom'},
>                                   'date': '2013-11-25'}],
>     'release-group': {   'id': '81f9c781-683e-4a4e-ba86-799e3c4c4be9',
>                          'primary-type': 'Album',
>                          'type': 'Album'},
>     'status': 'Official',
>     'title': 'Midnight Memories: The Ultimate Edition'}
> None
> {   'country': 'GB',
>     'date': '2013-11-25',
>     'id': 'cba1b4c6-6807-409a-9c4a-fce63632487a',
>     'medium-list': [   {   'format': 'CD',
>                            'position': '1',
>                            'track-count': 14,
>                            'track-list': [   {   'id': '43da2586-6a6a-4fbc-b98a-086433f6d671',
>                                                  'length': '245493',
>                                                  'number': '2',
>                                                  'title': 'Story of My Life',
>                                                  'track_or_recording_length': '245493'}]}],
>     'medium-track-count': 14,
>     'release-event-list': [   {   'area': {   'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed',
>                                               'iso-3166-1-code-list': [   'GB'],
>                                               'name': 'United Kingdom',
>                                               'sort-name': 'United Kingdom'},
>                                   'date': '2013-11-25'}],
>     'release-group': {   'id': '81f9c781-683e-4a4e-ba86-799e3c4c4be9',
>                          'primary-type': 'Album',
>                          'type': 'Album'},
>     'status': 'Official',
>     'title': 'Midnight Memories'}
> None
> {   'country': 'US',
>     'date': '2013-11-25',
>     'id': 'e017e042-3c9b-4a93-ba3e-c4e088c78cc6',
>     'medium-list': [   {   'format': 'CD',
>                            'position': '1',
>                            'track-count': 14,
>                            'track-list': [   {   'id': '70bcca2b-acd2-4bd9-8216-b8b81c1a58ca',
>                                                  'length': '245493',
>                                                  'number': '2',
>                                                  'title': 'Story of My Life',
>                                                  'track_or_recording_length': '245493'}]}],
>     'medium-track-count': 14,
>     'release-event-list': [   {   'area': {   'id': '489ce91b-6658-3307-9877-795b68554c98',
>                                               'iso-3166-1-code-list': [   'US'],
>                                               'name': 'United States',
>                                               'sort-name': 'United States'},
>                                   'date': '2013-11-25'}],
>     'release-group': {   'id': '81f9c781-683e-4a4e-ba86-799e3c4c4be9',
>                          'primary-type': 'Album',
>                          'type': 'Album'},
>     'status': 'Official',
>     'title': 'Midnight Memories'}
> None
> {   'country': 'XE',
>     'date': '2013-11-25',
>     'id': '13733f3f-7bef-487c-8f73-ab2d6a4aa133',
>     'medium-list': [   {   'format': 'CD',
>                            'position': '1',
>                            'track-count': 14,
>                            'track-list': [   {   'id': '140ccdfc-8eae-4914-8b0c-0be93e1fdc75',
>                                                  'length': '245493',
>                                                  'number': '2',
>                                                  'title': 'Story of My Life',
>                                                  'track_or_recording_length': '245493'}]}],
>     'medium-track-count': 14,
>     'release-event-list': [   {   'area': {   'id': '89a675c2-3e37-3518-b83c-418bad59a85a',
>                                               'iso-3166-1-code-list': [   'XE'],
>                                               'name': 'Europe',
>                                               'sort-name': 'Europe'},
>                                   'date': '2013-11-25'}],
>     'release-group': {   'id': '81f9c781-683e-4a4e-ba86-799e3c4c4be9',
>                          'primary-type': 'Album',
>                          'type': 'Album'},
>     'status': 'Official',
>     'title': 'Midnight Memories'}

thanks!

**Comment by mineo** [comment]
If you do

```
import logging
logging.basicConfig(level=logging.DEBUG)
```
somewhere, pymbngs will log the URLs that it accesses internally. In your case, that's http://musicbrainz.org/ws/2/recording/?limit=5&query=artist%3A%22One+Direction%22+AND+recording%3A%22Story+of+My+Life%22+AND+type%3A%22Album%22+AND+country%3A%22US%22+AND+format%3A%22cd%22

As you can see, `country` is not ignored, but the response contains all releases of the only recording result. If `country` was ignored, you'd end up on http://musicbrainz.org/ws/2/recording/?limit=5&query=artist%3A%22One+Direction%22+AND+recording%3A%22Story+of+My+Life%22+AND+type%3A%22Album%22+AND+format%3A%22cd%22 with 2 results instead of one.
