### ISSUE TITLE
Port Unicode punctuation characters to ASCII from Picard

### ISSUE THREAD

**Issue by dgasaway** [alastair/python-musicbrainzngs#228]
Would the project be open to porting the code from Picard to implement 'Convert Unicode punctuation characters to ASCII' to python-musicbrainzngs?  It would be an optional feature, of course.  I could port it to my own code, but it seems a useful feature that other clients could use.

**Comment by alastair** [comment]
I don't think that this fits in this project - we are mostly interested in being only a wrapper around the data that the webservice wants. If someone is interested in publishing this as a separate library then that'd be great!
Thanks

**Comment by sampsyo** [comment]
I agree that this probably shouldn't go in an MB client library. If you're curious, @dgasaway, this is something we offer as an option in beets too—you can see how we do it there (key word: "asciify"). We use the excellent [Unidecode][] library.

[unidecode]: https://pypi.org/project/Unidecode/

**Comment by dgasaway** [comment]
I already ported it into my library/tools.  It's not substantial enough to stand as a separate library.  Thanks for the pointer @sampsyo, but Unidecode is not what I'm looking for.  I'm only concerned with Unicode punctuation - I do not want to remove all Unicode.

**Comment by alastair** [comment]
OK, no problem. thanks for your offer, @dgasaway!
