### ISSUE TITLE
What does '<ws2:release-group>, uncaught attribute type-id' mean?

### ISSUE THREAD

**Issue by amiantos** [alastair/python-musicbrainzngs#229]
I'm running a task and I'm getting a lot of these in the INFO logs.

`<ws2:release-group>, uncaught attribute type-id`
`<ws2:artist>, uncaught attribute type-id`

Are they anything to worry about?

**Comment by alastair** [comment]
No, no problem. It just indicates that there are some fields in the returned XML that are not converted into fields in the python objects returned by the methods. You can change the logging level of the logger called `musicbrainzngs` to `WARNING` to prevent these messages from appearing
