### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by gerion0** [alastair/python-musicbrainzngs#250]
There were quite a few changes since 2016. Can you make another release?

**Comment by alastair** [comment]
yeah, absolutely! In the next week I’ll take a look at what’s been merged and what’s waiting and see if I can pull something together. Please ping me again if I don’t do it in a few weeks

**Comment by gerion0** [comment]
Friendly ping ;)

**Comment by alastair** [comment]
Thanks for the reminder, this week I'm merging old PRs and adding important fixes. I'll try for a release this weekend or next!

**Comment by gerion0** [comment]
Hmm, I hope you don't mind, if I ping again ;)

**Comment by alastair** [comment]
Thanks for the reminder! I wanted to merge some pull requests and add some new features but I realised that I wasn't getting to those tasks, so I just released 0.7 with what was already committed to master!
