### ISSUE TITLE
get_release_group_image_list gives HTTP 404 if no images exist

### ISSUE THREAD

**Issue by mueslo** [alastair/python-musicbrainzngs#260]
```
  File "test_musicbrainz.py", line 17, in get_artwork
    data = musicbrainzngs.get_release_group_image_list(release_group_id)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/caa.py", line 125, in get_release_group_image_list
    return _caa_request(releasegroupid, entitytype="release-group")
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/caa.py", line 79, in _caa_request
    resp = musicbrainz._safe_read(opener, req, None)
  File "/usr/lib/python3.8/site-packages/musicbrainzngs/musicbrainz.py", line 503, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 404: NOT FOUND
```
`musicbrainzngs` version: 0.7.1

Example release-group ID: ad615641-74ca-4ca1-8450-128b3ae1dc77

**Comment by mueslo** [comment]
Okay, it's not very obvious, but I think https://python-musicbrainzngs.readthedocs.io/en/latest/api/#musicbrainzngs.get_release_group_image_list which says `No release exists with an MBID of releaseid` is meant to be read in the context of the CAA, not MB.

**Comment by mineo** [comment]
No, you're right, the docstring in this case is misleading. I've opened #261 to clarify it. The documentation of the CAA itself is more clear:

> - 404 if either there is no release group with this MBID, or the community have not chosen an image to represent the release group. 

https://musicbrainz.org/doc/Cover_Art_Archive/API#.2Frelease-group.2F.7Bmbid.7D.2F
