### ISSUE TITLE
Rework examples/demos

### ISSUE THREAD

**Issue by alastair** [alastair/python-musicbrainzngs#51]
Move examples from a single file to a series of demos that use all the features that are available

Features that should be demonstrated:

 * [x] Get
 * [x] Includes
 * [x] Release status / type
 * [ ] Browse
 * [ ] Paging
 * [ ] Submission
 * [x] Search
 * [x] Advanced search
 * [x] Setting passwords
 * [x] Collections

**Comment by JonnyJD** [comment]
Closing this.

We still don't have examples using browsing/paging and submission in the [examples directory](https://github.com/alastair/python-musicbrainzngs/tree/master/examples).
However we have documented this directly in the [documentation](http://python-musicbrainzngs.readthedocs.org/en/latest/usage/#browsing).
